/**
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

#include <iostream>
#include <vector>
#include <stdexcept>

namespace
{

/**
 *
 */
int calculateNewFibonacciNumber(const std::vector<int>& fibonacciSequence)
{
    const size_t size = fibonacciSequence.size();
    if (size < 2)
        throw std::runtime_error(
                "input fibonacci sequence's size must be greater than 2");
    return fibonacciSequence[size - 2] + fibonacciSequence[size - 1];
}

} // namespace

namespace problem_2
{

/**
 *
 */
int solve()
{
    //
    std::cout << "started " << __FUNCTION__ << std::endl;

    //----------------------------------
    // generate Fibonacci Sequence
    //----------------------------------
    const int limit = 4000000;
    std::vector<int> fibonacciSequence =
    { 1, 2 };
    while (true)
    {
        const int num = calculateNewFibonacciNumber(fibonacciSequence);
        fibonacciSequence.push_back(num);

        if (num > limit)
            break;
    }
    // show sequence
    std::cout << "sequence: " << std::endl;
    for (int num : fibonacciSequence)
    {
        std::cout << num << ", ";
    }
    std::cout << std::endl;

    //----------------------------------
    // calculate summation of Fibonacci Sequence
    //----------------------------------
    int sum = 0;
    for (int e : fibonacciSequence)
    {
        if (e % 2 == 0)
            sum += e;
    }
    std::cout << "result: " << sum << std::endl;

    //
    std::cout << "finished " << __FUNCTION__ << std::endl;

    return 0;
}

} // namespace problem_2
